-- Retrait des decomptes figes des commentaires — 2026-08-25
--
-- POURQUOI. Les commentaires du schema partent DANS L'INSTRUCTION SYSTEME : les
-- vues metier en entier, les reflets de table par leur premiere phrase. Or 70 de
-- ces resumes portaient un decompte date du 2026-08-15 (« 105353 lignes mesurees
-- le ... »). Le modele lisait donc un nombre avant meme d'interroger la base — et
-- pouvait le reciter au lieu de compter.
--
-- Ces nombres ont derive en dix jours. Mesure du 2026-08-25 : 21 des 69 decomptes
-- etaient FAUX. note annoncait 105 353 pour 105 493 reelles ; type_document
-- annoncait 23 pour 9 ; historique_inscription annoncait 9 pour 0 ; et
-- assistant_reglages etait declaree « TABLE VIDE » alors qu'elle porte une ligne.
--
-- On retire le chiffre, on garde le sens. Une table vide devient « sans donnee au
-- dernier releve, confirme par COUNT(*) » : l'information reste utile au modele
-- pour choisir ou chercher, sans lui donner un nombre a repeter.
--
-- Migration purement additive : uniquement des COMMENT ON. Aucune structure,
-- aucune donnee, aucun privilege n'est touche. Rejouable sans effet de bord.

COMMENT ON VIEW assistant.t_accessoire IS 'Article du stock scolaire. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_affectation_charge_pedagogique IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module Enseignants (RH), pas encore utilisé localement. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_annee_bac IS 'Référentiel des années d''obtention du bac. etudiant.annee_bac est un varchar libre, PAS une FOREIGN KEY vers cette table. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_anneeacademique IS 'Référentiel des années académiques (ex. ''2025-2026''). Référencée par de très nombreuses tables (paiement, etudiant, niveau, classe, inscription_annuelle..). Contrainte UNIQUE(annee). Absente du rang A/B/C/D d''origine, ajoutée en rang C. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_anneeacademique_site IS 'Ouverture d''une année académique pour un site donné. RÈGLE MÉTIER GARANTIE PAR LE SCHÉMA (index unique partiel) : au plus une ligne à l''état ''en cour'' par site. — Cloisonnée par site_id.';
COMMENT ON VIEW assistant.t_assistant_google_compte IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Migration très récente (2026-08-12e_assistant_google.sql) : aucun compte Google configuré localement. — Cloisonnée par site_id. Colonne(s) retirée(s) : jeton_rafraichissement.';
COMMENT ON VIEW assistant.t_assistant_reglages IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Migration très récente (2026-08-13d_assistant_reglages.sql) : aucun réglage de site initialisé localement. — Cloisonnée par site_id.';
COMMENT ON VIEW assistant.t_besoin_enseignant IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module Enseignants (RH), pas encore utilisé localement. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_caisse IS 'Caisse physique/logique d''un site, point d''encaissement des paiements. — Cloisonnée par site_id.';
COMMENT ON VIEW assistant.t_candidature_diplome IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module Enseignants (RH), pas encore utilisé localement. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_candidature_enseignant IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module Enseignants (RH), introduit par migrations/2026-08-11_module_enseignants.sql, pas encore utilisé localement. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_candidature_filiere IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module Enseignants (RH), pas encore utilisé localement. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_categorie IS 'Référentiel des catégories d''UE (non représentatif). — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_classe IS 'Classe pédagogique (année académique x niveau x filière). Recréée chaque année académique (filiere reste permanente, voir la documentation interne). — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_commande_fournisseur IS 'Commande passée à un fournisseur (module peu utilisé). — Cloisonnée par site_id.';
COMMENT ON VIEW assistant.t_contrat_classe IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module Enseignants (RH), pas encore utilisé localement. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_contrat_enseignant IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module Enseignants (RH), pas encore utilisé localement. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_curcus IS 'Référentiel des types de parcours. curcus_id est décliné en FOREIGN KEY sur plusieurs tables mais reste NON ALIMENTÉ sur inscription_annuelle localement. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_decoupage_groupe IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Fonctionnalité de répartition automatique de groupes, jamais déclenchée localement (A CONFIRMER). — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_departement IS 'Département pédagogique au sein d''une école. Contrainte UNIQUE(ecole_id, nom). — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_distribution IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module stock, aucune distribution enregistrée localement (module globalement peu alimenté : accessoire 4 lignes, fournisseur 1 ligne). — Cloisonnée par l''étudiant rattaché.';
COMMENT ON VIEW assistant.t_document IS 'Checklist des pièces administratives d''un dossier étudiant à l''admission (4 colonnes texte), référencée par etudiant.document_id. — Cloisonnée par rattachement indirect.';
COMMENT ON VIEW assistant.t_document_etudiant IS 'Suivi de fourniture d''un document administratif (par type_document) par un étudiant. Contrainte UNIQUE(etudiant_id, type_document_id). — Cloisonnée par l''étudiant rattaché.';
COMMENT ON VIEW assistant.t_ecole IS 'École au sein de l''établissement. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_emplacement_stock IS 'Emplacement physique de stockage rattaché à un site. — Cloisonnée par site_id.';
COMMENT ON VIEW assistant.t_emploi_du_temps IS 'Fichier d''emploi du temps uploadé pour un groupe (dépôt simple). NE PAS CONFONDRE avec seance_edt/trame_edt (module Enseignants, planification structurée, vide localement). — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_enseignant IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module Enseignants (RH), pas encore utilisé localement. NE PAS CONFONDRE avec professeur (module historique notes/enseignements, 115 lignes). — Cloisonnée par site_id.';
COMMENT ON VIEW assistant.t_enseignement IS 'Rattachement (professeur x matière x groupe) pour une année académique. Contrainte UNIQUE(professeur_id, matiere_id, groupe_id, annee_academique). — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_etablissement_origine IS 'Référentiel des établissements d''origine des étudiants. ATTENTION : etudiant.etablissement_origine est un champ TEXTE LIBRE, PAS une FOREIGN KEY vers cette table malgré le nom identique. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_etudiant IS 'Position académique et administrative COURANTE d''un étudiant (1 ligne par étudiant). PAS un historique : voir inscription_annuelle et historique_inscription pour l''historique par année, et public.vue_position_academique comme SEULE source de lecture recommandée pour les données historiques. Beaucoup de colonnes de type référence (site_id, annee_academique_id, groupe_id, niveau_id, document_id, scolarite_id, curcus_id, id_filiere) n''ont AUCUNE contrainte FOREIGN KEY déclarée. — Cloisonnée par site_id. Colonne(s) retirée(s) : password.';
COMMENT ON VIEW assistant.t_etudiant_email_backup IS 'Sauvegarde ponctuelle des adresses de courriel d''etudiants. Table figee, sans cle primaire : elle ne reflete pas l''etat courant, qui est dans etudiant.email. Cloisonnee par l''etudiant rattache.';
COMMENT ON VIEW assistant.t_filiere IS 'Filière de formation, PERMANENTE d''une année sur l''autre (contrairement à classe/niveau/tarif/maquette). — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_fournisseur IS 'Fournisseur pour les commandes de stock (module peu utilisé). — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_groupe IS 'Groupe d''étudiants au sein d''une classe. Référencé par etudiant.groupe_id SANS contrainte FOREIGN KEY (7 orphelins observés, voir etudiant). — Cloisonnée par rattachement indirect.';
COMMENT ON VIEW assistant.t_historique_inscription IS 'Position académique FIGÉE d''un étudiant pour une année académique clôturée, alimentée à chaque réinscription/clôture. Combinée à etudiant par public.vue_position_academique (UNION ALL, filtrée sur type_evenement=''cloture'') : SEULE source de lecture recommandée pour les données historiques. ATTENTION — le commentaire existant sur assistant.v_activite_agents affirme que cette table est vide : c''est désormais FAUX, commentaire obsolète signalé pour action future. — Cloisonnée par l''étudiant rattaché.';
COMMENT ON VIEW assistant.t_historique_operations_admin IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Aucun changement de filière/parcours/cycle exceptionnel (hors réinscription) enregistré localement, voir la documentation interne. — Cloisonnée par l''étudiant rattaché.';
COMMENT ON VIEW assistant.t_inscription_annuelle IS 'Position académique d''un étudiant POUR UNE ANNÉE ACADÉMIQUE DONNÉE (snapshot annuel). RÈGLE ANTI DOUBLE-COMPTAGE : contrainte UNIQUE(etudiant_id, annee_academique_id) — une seule ligne par étudiant et par année. Les données locales proviennent d''une migration technique (type_evenement = ''migration_position_courante''/''migration_historique''), pas encore du flux normal de réinscription. — Cloisonnée par site_id.';
COMMENT ON VIEW assistant.t_kit IS 'Frais/dépôt de kit scolaire d''un étudiant pour une année académique. Certaines années peuvent être suspendues pour ce module (variable KIT_ANNEES_SUSPENDUES). — Cloisonnée par l''étudiant rattaché.';
COMMENT ON VIEW assistant.t_ligne_commande_fournisseur IS 'Ligne de détail (accessoire x quantité) d''une commande fournisseur. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_ligne_distribution IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module stock, voir distribution. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_maquette IS 'Maquette pédagogique (filière x niveau x année académique), regroupant les UE. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_matiere IS 'Matière (ECUE) rattachée à une UE. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_memoire IS 'Dépôt de mémoire de fin d''études d''un étudiant pour une année académique, avec circuit de validation (statut). — Cloisonnée par l''étudiant rattaché.';
COMMENT ON VIEW assistant.t_mouvement_stock IS 'Mouvement de stock d''un accessoire (réception/distribution/ajustement/transfert) (module peu utilisé localement). — Cloisonnée par rattachement indirect.';
COMMENT ON VIEW assistant.t_niveau IS 'Niveau d''études (filière x année académique x site). Recréé chaque année académique comme classe/tarif/maquette. — Cloisonnée par site_id.';
COMMENT ON VIEW assistant.t_note IS 'Une évaluation d''un étudiant dans un enseignement donné. AUCUNE clé primaire ni contrainte FOREIGN KEY déclarée sur cette table (seulement 2 contraintes CHECK sur les plages de valeurs). Les colonnes note1/note2/partiel ne sont pas toutes pertinentes pour chaque matière : voir matiere.type_evaluation avant tout calcul de moyenne. — Cloisonnée par l''étudiant rattaché.';
COMMENT ON VIEW assistant.t_offre_emploi_enseignant IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module Enseignants (RH), pas encore utilisé localement. — Cloisonnée par site_id.';
COMMENT ON VIEW assistant.t_paiement IS 'Un encaissement individuel via le module Caisse. ATTENTION — NE COUVRE PAS tout l''historique des règlements : les montants repris à la mise en service n''y figurent pas. SUM(paiement.montant) N''EST PAS le chiffre d''affaires / total des recettes de l''établissement. La RÉFÉRENCE pour ''chiffre d''affaires'', ''recettes'', ''total encaissé'' est scolarite.scolarite_verse (voir public.vue_position_academique). À utiliser pour l''activité de caisse (encaissements du jour/du mois, par caissier, par mode de paiement). etudiant_id et recu_id référencent etudiant/recu SANS contrainte FOREIGN KEY (fiable en pratique : 0 orphelin observé). — Cloisonnée par l''étudiant rattaché.';
COMMENT ON VIEW assistant.t_pays IS 'Référentiel des pays (nationalité, code ISO). — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_permission IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Les rôles semblent gérés directement via utilisateur.role_id/role plutôt que via ce système de permissions granulaires (A CONFIRMER). — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_prise_en_charge IS 'Réduction ou prise en charge institutionnelle des frais de scolarité (bourse, convention entreprise). Mouvement DISTINCT des paiements réels (ne pas combiner avec paiement.montant pour un coût total). — Cloisonnée par l''étudiant rattaché.';
COMMENT ON VIEW assistant.t_professeur IS 'Enseignant utilisé par le module notes/enseignements historique (enseignement.professeur_id). NE PAS CONFONDRE avec la table enseignant (module RH plus récent, vide localement). — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_reception_fournisseur IS 'Réception physique d''une commande fournisseur. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_recu IS 'Justificatif d''encaissement associé à un paiement. AUCUNE CONTRAINTE DU TOUT sur cette table : ni PRIMARY KEY, ni UNIQUE, ni FOREIGN KEY, ni même un index. Environ 110 reçus ne sont référencés par aucun paiement. — Cloisonnée par rattachement indirect.';
COMMENT ON VIEW assistant.t_resultat IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Ses colonnes (moyenne, decision, etudiant_id, session_id) font doublon fonctionnel avec inscription_annuelle.moyenne_annuelle/decision_annuelle — hypothèse d''une table supplantée, NON CONFIRMÉE. Ne pas s''appuyer dessus. — Cloisonnée par l''étudiant rattaché.';
COMMENT ON VIEW assistant.t_role IS 'Référentiel des rôles applicatifs. Référencé par utilisateur.role_id SANS contrainte FOREIGN KEY. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_rolepermission IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Voir permission. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_salle IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module Enseignants (planification), pas encore utilisé localement. — Cloisonnée par site_id.';
COMMENT ON VIEW assistant.t_scolarite IS 'Position financière de scolarité d''un étudiant (montant dû/versé/restant). RÔLE CONFIRMÉ par public.vue_position_academique (LEFT JOIN scolarite ON scolarite.id = etudiant.scolarite_id) : TABLE DE RÉFÉRENCE pour le chiffre d''affaires / total encaissé de l''établissement (scolarite_verse), PAS paiement. Relation 1:1 voulue avec etudiant via etudiant.scolarite_id, mais AUCUNE contrainte FOREIGN KEY déclarée sur cette table. — Cloisonnée par rattachement indirect.';
COMMENT ON VIEW assistant.t_seance_edt IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module Enseignants (planification), pas encore utilisé localement. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_semestre IS 'Référentiel des semestres (S1/S2). — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_serie_bac IS 'Référentiel des séries de baccalauréat. etudiant.serie_bac est un varchar libre, PAS une FOREIGN KEY vers cette table. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_session IS 'Référentiel des sessions d''examen — explique pourquoi note.session_id n''a qu''une seule valeur distincte localement. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_session_caisse IS 'Session d''ouverture/fermeture d''une caisse par un caissier (arrêté de caisse). caissier_id référence utilisateur.id SANS contrainte FOREIGN KEY. — Cloisonnée par rattachement indirect.';
COMMENT ON VIEW assistant.t_site IS 'Site physique d''implantation. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_tarif IS 'Barème tarifaire de scolarité pour un niveau donné. Contrainte UNIQUE(niveau_id) : au plus un tarif par niveau. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_trame_edt IS 'Table sans donnee au dernier releve — confirme par COUNT(*) avant de l''affirmer. Module Enseignants (planification), pas encore utilisé localement. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_type_document IS 'Référentiel des types de documents administratifs attendus. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_typefiliere IS 'Référentiel des types de filière. Coexiste avec niveau.type_filiere (varchar libre) — ne pas confondre. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_ue IS 'Unité d''Enseignement, regroupement de matières au sein d''une maquette. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.t_ville IS 'Référentiel des villes. — NON cloisonnée : référentiel partagé ou structure commune aux sites.';
COMMENT ON VIEW assistant.v_etudiants IS 'Etudiants du site, avec leur position financiere. UNE LIGNE PAR ETUDIANT ET PAR ANNEE : l''effectif se compte donc avec COUNT(*), jamais avec COUNT(DISTINCT matricule). standing = ''Inscrit'' pour les effectifs. PIEGE : le matricule n''est PAS une cle unique et ne doit servir a AUCUN comptage — plusieurs centaines sont inexploitables (vides, ou composes uniquement de zeros) et certaines valeurs sont partagees par plusieurs etudiants. Compter les matricules distincts sous-estime l''effectif. a_photo indique si une photo est disponible pour cet etudiant : une minorite en a une. Pour montrer une fiche avec photo, filtrer WHERE a_photo. Tu ne connais AUCUN de ces decomptes par coeur : compte-les.';
COMMENT ON VIEW assistant.v_personnes IS 'Annuaire unifie : etudiants, agents et enseignants dans une seule vue. POINT D''ENTREE OBLIGATOIRE pour retrouver quelqu''un. Ecrire : WHERE assistant.correspond(nom_complet, ''Boga Christian''). Cette fonction compare des MOTS ENTIERS dans un ordre libre — n''utilise PAS LIKE, qui ramenait « MANIGA » pour « Mani » et echouait des que deux mots etaient cites dans le desordre. TOUJOURS trier par priorite d''abord (1 agent, 2 enseignant, 3 etudiant) : les etudiants sont deux ordres de grandeur plus nombreux que les agents, et sans ce tri un nom repandu ne ramene que des etudiants.';
